groups:
  - name: node_alerts
    rules:
      - alert: High Memory Usage (Instance - Critical)
        expr: node_memory_MemAvailable_bytes{nodename="main-server"} / node_memory_MemTotal_bytes{nodename="main-server"} < 0.1
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Low memory on {{ $labels.nodename }}"
          description: "Memory available < 10% for 10 minutes on {{ $labels.instance }}"

      - alert: High CPU Usage (Instance - Critical)
        expr: 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m]))) > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 2 minutes (current value: {{ $value }}%)"

      - alert: High CPU Usage (Instance - Warning)
        expr: 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 75
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 75% for more than 5 minutes (current value: {{ $value }}%)"

      - alert: High Memory Usage (Container - Warning)
        expr: container_memory_usage_bytes{container!="",pod!=""} > 1024000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container {{ $labels.container }}"
          description: "Container {{ $labels.container }} is using > 1024MB memory for 5 minutes"

      - alert: High CPU Usage (Container - Critical)
        expr: rate(container_cpu_usage_seconds_total{container!="",pod!=""}[5m]) * 100 > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in container {{ $labels.container }}"
          description: "Container {{ $labels.container }} is using > 90% CPU for 2 minutes"
